// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package net.mymonopoly.promo;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import net.mymonopoly.promo.BrowserHeaders;
import net.mymonopoly.promo.BrowserHeadersDataOnDemand;
import net.mymonopoly.promo.Email;
import net.mymonopoly.promo.EmailDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect BrowserHeadersDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BrowserHeadersDataOnDemand: @Component;
    
    private Random BrowserHeadersDataOnDemand.rnd = new SecureRandom();
    
    private List<BrowserHeaders> BrowserHeadersDataOnDemand.data;
    
    @Autowired
    private EmailDataOnDemand BrowserHeadersDataOnDemand.emailDataOnDemand;
    
    public BrowserHeaders BrowserHeadersDataOnDemand.getNewTransientBrowserHeaders(int index) {
        BrowserHeaders obj = new BrowserHeaders();
        setEmail(obj, index);
        setName(obj, index);
        setVal(obj, index);
        return obj;
    }
    
    public void BrowserHeadersDataOnDemand.setEmail(BrowserHeaders obj, int index) {
        Email email = emailDataOnDemand.getRandomEmail();
        obj.setEmail(email);
    }
    
    public void BrowserHeadersDataOnDemand.setName(BrowserHeaders obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void BrowserHeadersDataOnDemand.setVal(BrowserHeaders obj, int index) {
        String val = "val_" + index;
        obj.setVal(val);
    }
    
    public BrowserHeaders BrowserHeadersDataOnDemand.getSpecificBrowserHeaders(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        BrowserHeaders obj = data.get(index);
        Long id = obj.getId();
        return BrowserHeaders.findBrowserHeaders(id);
    }
    
    public BrowserHeaders BrowserHeadersDataOnDemand.getRandomBrowserHeaders() {
        init();
        BrowserHeaders obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return BrowserHeaders.findBrowserHeaders(id);
    }
    
    public boolean BrowserHeadersDataOnDemand.modifyBrowserHeaders(BrowserHeaders obj) {
        return false;
    }
    
    public void BrowserHeadersDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = BrowserHeaders.findBrowserHeadersEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'BrowserHeaders' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<BrowserHeaders>();
        for (int i = 0; i < 10; i++) {
            BrowserHeaders obj = getNewTransientBrowserHeaders(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
